# Generated by Django 6.0.3 on 2026-06-16 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0008_agendamento_origem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('cnpj', models.CharField(blank=True, default='', max_length=18)),
                ('email', models.EmailField(max_length=254)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Salão',
                'verbose_name_plural': 'Salões',
            },
        ),
        migrations.RemoveConstraint(
            model_name='agendamento',
            name='unique_agendamento_data_horario',
        ),
        migrations.AlterField(
            model_name='notificacaoexclusao',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='horario_duplo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='admin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='horariobloqueado',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='agendamento.tenant'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='agendamento.tenant'),
        ),
        migrations.AddField(
            model_name='horariobloqueado',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_bloqueados', to='agendamento.tenant'),
        ),
        migrations.AddField(
            model_name='servico',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='agendamento.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='horariobloqueado',
            unique_together={('tenant', 'data', 'horario')},
        ),
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=models.UniqueConstraint(fields=('tenant', 'data', 'horario'), name='unique_agendamento_tenant_data_horario'),
        ),
    ]
