# Generated by Django 6.0.3 on 2026-06-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0009_tenant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='cnpj',
        ),
        migrations.AddField(
            model_name='tenant',
            name='nome_responsavel',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='termos_aceitos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='termos_aceitos_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tipo_negocio',
            field=models.CharField(choices=[('salao', 'Salão de Beleza'), ('barbearia', 'Barbearia'), ('studio', 'Studio de Unhas'), ('outro', 'Outro')], default='salao', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
