# Generated by Django 6.0.3 on 2026-06-25 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0010_remove_tenant_cnpj_tenant_nome_responsavel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoConvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('usado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usado_por', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codigo_convite', to='agendamento.tenant')),
            ],
            options={
                'verbose_name': 'Código de Convite',
                'verbose_name_plural': 'Códigos de Convite',
            },
        ),
    ]
