# Generated by Django 6.0.3 on 2026-07-18 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0011_codigoconvite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSalao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publico', models.CharField(blank=True, choices=[('homens', 'Homens'), ('mulheres', 'Mulheres'), ('ambos', 'Homens e Mulheres')], default='ambos', max_length=20)),
                ('endereco', models.CharField(blank=True, default='', max_length=200)),
                ('instagram', models.CharField(blank=True, default='', max_length=60)),
                ('cor_primaria', models.CharField(blank=True, default='#0d6efd', help_text='Cor em hexadecimal. Ex: #0d6efd', max_length=7)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao', to='agendamento.tenant')),
            ],
            options={
                'verbose_name': 'Configuração do Salão',
                'verbose_name_plural': 'Configurações dos Salões',
            },
        ),
    ]
