# Generated by Django 6.0.3 on 2026-07-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0012_configuracaosalao'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosalao',
            name='nome_exibicao',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='configuracaosalao',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='configuracaosalao',
            name='tipo_negocio',
            field=models.CharField(blank=True, choices=[('salao', 'Salão de Beleza'), ('barbearia', 'Barbearia'), ('studio', 'Studio de Unhas'), ('esmalteria', 'Esmalteria'), ('outro', 'Outro')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='configuracaosalao',
            name='cor_primaria',
            field=models.CharField(blank=True, default='#0d6efd', max_length=7),
        ),
    ]
