# Generated by Django 6.0.3 on 2026-07-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0013_configuracaosalao_nome_exibicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='excluido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
