# Generated by Django 6.0.3 on 2026-08-10 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0015_periodobloqueio_horariofuncionamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('bloqueado', 'Bloqueado (aguardando escolha de pagamento)'), ('aguardando_pagamento', 'Aguardando Pagamento'), ('confirmado', 'Confirmado'), ('expirado', 'Expirado'), ('cancelado', 'Cancelado')], default='bloqueado', max_length=20)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamento.cliente')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamento.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='SlotReservado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='agendamento.pedidoreserva')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamento.servico')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamento.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'servico', 'data', 'horario'), name='unique_slot_tenant_servico_data_horario')],
            },
        ),
    ]
