# Generated by Django 6.0.3 on 2026-08-12 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0016_pedidoreserva_slotreservado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_payment_id', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('pendente', 'Aguardando pagamento'), ('aprovado', 'Aprovado'), ('expirado', 'Expirado'), ('cancelado', 'Cancelado')], default='pendente', max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('qr_code', models.TextField(blank=True, default='')),
                ('qr_code_base64', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='agendamento.pedidoreserva')),
            ],
        ),
    ]
