# Generated by Django 6.0.3 on 2026-08-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0017_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='horario_fim',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
