# Generated by Django 6.0.3 on 2026-07-23 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamento', '0014_tenant_excluido_em'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('senha_hash', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ultimo_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Super Admin',
                'verbose_name_plural': 'Super Admins',
            },
        ),
        migrations.CreateModel(
            name='StatusSalao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('teste', 'Em teste'), ('congelado', 'Congelado'), ('suspenso', 'Suspenso'), ('cancelado', 'Cancelado')], default='teste', max_length=20)),
                ('pagamento_em_dia', models.BooleanField(default=True)),
                ('ultimo_pagamento', models.DateField(blank=True, null=True)),
                ('vencimento', models.DateField(blank=True, null=True)),
                ('observacoes_internas', models.TextField(blank=True, default='')),
                ('congelado_em', models.DateTimeField(blank=True, null=True)),
                ('congelado_motivo', models.CharField(blank=True, default='', max_length=200)),
                ('ultimo_acesso', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status_admin', to='agendamento.tenant')),
            ],
            options={
                'verbose_name': 'Status do Salão',
                'verbose_name_plural': 'Status dos Salões',
            },
        ),
        migrations.CreateModel(
            name='LogAdministrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('congelar', 'Congelou a conta'), ('reativar', 'Reativou a conta'), ('suspender', 'Suspendeu a conta'), ('excluir', 'Excluiu o salão'), ('editar', 'Editou informações'), ('codigo', 'Gerou código de ativação'), ('login', 'Login no Painel Master')], max_length=20)),
                ('detalhes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agendamento.tenant')),
                ('super_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.superadminuser')),
            ],
            options={
                'verbose_name': 'Log Administrativo',
                'verbose_name_plural': 'Logs Administrativos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
